protected/modules/adminx24/controllers/DefaultController.php
<?php

class DefaultController extends AdminController
{

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', //Вход, Выход и страницу ошибок показываем всем, включая гостя
                'actions'=>array('login', 'logout', 'error'),
                'users'=>array('*'),
            ),
            array('allow', // Разрешим всё главному админу
                'roles' => array('admin'),
            ),

            array('deny',  // всё остальное всем запрещаем
                'users'=>array('*'),
            ),
        );
    }

	public function actionIndex()
	{
        $model = new Contacts('search');
		$this->render('index', array('model' => $model));
	}

    /**
     * Авторизация в админку
     */
    public function actionLogin()
    {
        $model=new LoginForm;

        // if it is ajax validation request
        if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if(isset($_POST['LoginForm']))
        {
            $model->attributes=$_POST['LoginForm'];
            if($model->validate() && $model->login())
            {

                if(str_replace('/', '', Yii::app()->request->baseUrl) == str_replace('/', '', Yii::app()->user->returnUrl))
                {
                    $this->redirect($this->createUrl('projects/index'));
                }
                else
                {
                    $this->redirect(Yii::app()->user->returnUrl);
                }

            }
        }
        // display the login form
        $this->renderPartial('login',array('model'=>$model));
    }

    /**
     * Выход из админки
     */
    public function actionLogout()
    {
        Yii::app()->user->logout();
        $this->redirect($this->createUrl('default/login'));
    }

    /**
     * Страница обработки ошибок
     */
    public function actionError(){
        if($error=Yii::app()->errorHandler->error)
        {
            if(Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    public function actionAdd(){
        $model = new ContactSocial();
        if (Yii::app()->request->isPostRequest){
            $model->attributes = $_POST['ContactSocial'];
            if ($model->save()){
                //$this->redirect($this->createUrl('index'));
                echo json_encode($model->attributes);
            }else {
                echo json_encode(array('success' => false));
            }
        }
//        $this->render('update', array('model' => $model));
    }

    public function actionUpdate($id){
        $model = ContactSocial::model()->findByPk($id);

        if (Yii::app()->request->isPostRequest){
            $model->attributes = $_POST['ContactSocial'];
            Contacts::model()->updateByPk(1, $_POST['ContactSocial']);
            if ($model->save()){
                $this->redirect($this->createUrl('index'));
            }
        }

        $this->render('update', array('model' => $model));
    }

    public function actionDelete($id){
        $model = new ContactSocial();
        $model->deleteByPk($id);
        $this->redirect($this->createUrl("index"));
    }

    public function actionChangeIndex(){
        $model = new ContactSocial();
        $arr = $_POST;
        $cnt = 0;
        for ($i = 0; $i < count($arr['idReal']); $i++){
            $cnt++;
            $attr = $model->findByPk($arr['idReal'][$i]);
            foreach($attr as $k=>$v) $model->$k = $v;
            $model->position = $cnt;
            if ($model->updateByPk($arr['idReal'][$i], $model->attributes)) echo 'OK';
        }
    }

    public function actionLoadImage()
    {
        $file = GFileUploader::uploadImage('file');
        if(GFileUploader::validate($file))
        {
            $ext = strtolower(GFileUploader::$ext);
            $rand = time() . rand(0 , 10);
            $dp = GHelper::dynamicPath($rand);
            $basePath = dirname(Yii::app()->basePath);
            $filename = $rand . '.' . $ext;
            if(GFileUploader::saveFile($basePath . About::PATH_TO_IMAGE . '/', $filename))
            {
                GHelper::jsonSuccess(
                    array(
                        'image_url' => Yii::app()->baseUrl . About::PATH_TO_IMAGE . '/' . $filename,
                        'imageName' => $filename
                    )
                );
            }
        }
        GHelper::jsonError('Ошибка сохранения файла');
    }
}

protected/modules/adminx24/controllers/SlidersController.php
<?php

class SlidersController extends AdminController
{

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', //Вход, Выход и страницу ошибок показываем всем, включая гостя
                'actions'=>array('login', 'logout', 'error'),
                'users'=>array('*'),
            ),
            array('allow', // Разрешим всё главному админу
                'roles' => array('admin'),
            ),

            array('deny',  // всё остальное всем запрещаем
                'users'=>array('*'),
            ),
        );
    }

	public function actionIndex()
	{
		$this->render('index');
	}

    public function actionChangeIndex(){
        $model = new Sliders();
        $arr = $_POST;
        $cnt = 0;
        for ($i = 0; $i < count($arr['idReal']); $i++){
            $cnt++;
            $attr = $model->findByPk($arr['idReal'][$i]);
            foreach($attr as $k=>$v) $model->$k = $v;
            $model->position = $cnt;
            if ($model->updateByPk($arr['idReal'][$i], $model->attributes)) echo 'OK';
        }
    }

    public function actionDelete($id){
        $model = new Sliders();
        $model->deleteByPk($id);
    }
}

protected/modules/adminx24/views/layouts/main.php
<?php

    /**
     * @var $this AdminController
     */

?>
<!doctype html>
<html lang="<?= Yii::app()->language ?>">
<head>
    <meta charset="UTF-8">
    <?php Yii::app()->clientScript->registerCoreScript('jquery.ui'); ?>
    <script type="text/javascript" src="<?=Yii::app()->baseUrl?>/media/js/jquery-1.10.2.js"></script>
    <script type="text/javascript">
        var base_url = "<?= Yii::app()->baseUrl?>";
        var admin_url = "<?= $this->createUrl('default/index')?>";
        var token = "<?= Yii::app()->request->csrfToken?>";
    </script>
    <link rel="stylesheet" href="<?=Yii::app()->baseUrl?>/media/css/bootstrap.min.css"/>

    <!--<link rel="stylesheet" href="<?/*=Yii::app()->baseUrl*/?>/media/css/bootstrap-theme.min.css"/>-->
    <!--<link rel="stylesheet" href="<?/*=Yii::app()->baseUrl*/?>/media/css/flat-ui.css"/>-->
    <title><?=$this->pageTitle?></title>
    <?php
        Yii::app()->clientScript->scriptMap['jquery.js'] = false;
        GHelper::registerCSS(
            array(
                /*'bootstrap.min.css',
                'bootstrap-theme.min.css',*/
                //'theme.css',
                'flat-ui.css',
                'main_admin.css',
            )
        );
        GHelper::registerJS(
            array(
                'flat-ui/jquery.ui.touch-punch.min.js',

                'bootstrap.min.js',

                'flat-ui/bootstrap-select.js',
                'flat-ui/bootstrap-switch.js',
                'flat-ui/flatui-checkbox.js',
                'flat-ui/flatui-radio.js',
                'flat-ui/jquery.tagsinput.js',
                'flat-ui/jquery.placeholder.js',
                'flat-ui/jquery.stacktable.js',

                'main_admin.js',
            )
        );
    ?>
</head>
<body>
    <div id="wrap">
        <div class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!--<a href="#" class="navbar-brand"><?/*=Yii::app()->name*/?></a>-->
                </div>
                <div class="collapse navbar-collapse">
                    <?php
                        $this->widget('zii.widgets.CMenu',
                            array(
                                'htmlOptions' => array(
                                    'class' => 'nav navbar-nav',
                                ),
                                'items'=>array(
                                    array(
                                        'label'=>'На главную',
                                        'url'=>$this->createUrl('default/index'),
                                        'active' => (Yii::app()->controller->id == 'default' && Yii::app()->controller->action->id == 'index'),
                                    ),
                                    array(
                                        'label'=>'Тэги',
                                        'url'=>$this->createUrl('tags/index'),
                                        'active' => (Yii::app()->controller->id == 'tags'),
                                    ),
                                    array(
                                        'label'=>'Проекты',
                                        'url'=>$this->createUrl('projects/index'),
                                        'active' => (Yii::app()->controller->id == 'projects'),
                                    ),
                                    array(
                                        'label'=>'Слайдер',
                                        'url'=>$this->createUrl('sliders/index'),
                                        'active' => (Yii::app()->controller->id == 'sliders'),
                                    ),
                                    array(
                                        'label'=>'Контакты',
                                        'url'=>$this->createUrl('contacts/index'),
                                        'active' => (Yii::app()->controller->id == 'contacts'),
                                    ),
                                    array(
                                        'label'=>'О нас',
                                        'url'=>$this->createUrl('about/index'),
                                        'active' => (Yii::app()->controller->id == 'about'),
                                    ),
                                )
                            )
                        );
                    ?>
                    <div class="navbar-right navbar-form">
                        <a href="<?= $this->createUrl('default/logout') ?>" class="btn btn-default">Выход(<?=Yii::app()->user->name?>)</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="page-header">
                <h1><?=$this->title?></h1>
            </div>
            <div class="content">
                <?=$content?>
            </div>
        </div>
    </div>
    <div id="footer">
        <div class="container">
            <p class="text-muted">© <?=Yii::app()->name?></p>
        </div>
    </div>
</body>
</html>